export const bangladeshLocations = {
  Dhaka: {
    Dhaka: {
      'Dhanmondi': ['Dhanmondi R/A', 'Jigatola', 'Shankar', 'Science Lab', 'New Market Area'],
      'Gulshan': ['Gulshan-1', 'Gulshan-2', 'Banani', 'Baridhara', 'Niketan'],
      'Mirpur': ['Mirpur-1', 'Mirpur-2', 'Mirpur-10', 'Mirpur-11', 'Mirpur-12', 'Pallabi', 'Kazipara', 'Shewrapara'],
      'Uttara': ['Uttara Sector-1', 'Uttara Sector-3', 'Uttara Sector-4', 'Uttara Sector-7', 'Uttara Sector-10', 'Uttara Sector-13'],
      'Mohammadpur': ['Mohammadpur Town Hall', 'Tajmahal Road', 'Nurjahan Road', 'Japan Garden City'],
      'Motijheel': ['Motijheel C/A', 'Arambagh', 'Fakirapool', 'Paltan'],
      'Tejgaon': ['Tejgaon I/A', 'Farmgate', 'Kawran Bazar', 'Bijoy Nagar'],
      'Ramna': ['Shahbagh', 'Eskaton', 'Maghbazar', 'Siddeshwari'],
      'Lalbagh': ['Lalbagh Fort', 'Azimpur', 'Kamrangirchar'],
      'Wari': ['Wari', 'Narinda', 'Gandaria'],
      'Badda': ['Badda', 'Merul Badda', 'Middle Badda', 'Aftab Nagar'],
      'Khilgaon': ['Khilgaon', 'Tilpapara', 'Goran', 'Bashabo'],
      'Jatrabari': ['Jatrabari', 'Dholaipar', 'Shyampur'],
      'Sabujbagh': ['Sabujbagh', 'Shampur'],
      'Shah Ali': ['Shah Ali Mazar', 'Shahid Nagar'],
    },
    Gazipur: {
      'Gazipur Sadar': ['Joydebpur', 'Chowrasta', 'Basan', 'Tongi', 'Konabari'],
      'Kaliakair': ['Kaliakair', 'Mouchak'],
      'Kaliganj': ['Kaliganj', 'Nagari'],
      'Sreepur': ['Sreepur', 'Rajendrapur'],
    },
    Narayanganj: {
      'Narayanganj Sadar': ['Narayanganj Town', 'Chashara', 'Deobhog', 'Sagarpara'],
      'Siddhirganj': ['Siddhirganj', 'Adamjee'],
      'Fatullah': ['Fatullah', 'Panchabati'],
      'Araihazar': ['Araihazar', 'Brahmanpara'],
      'Rupganj': ['Rupganj', 'Kanchan'],
    },
    Tangail: {
      'Tangail Sadar': ['Tangail Town', 'Victoria Road'],
      'Madhupur': ['Madhupur', 'Madhupur Town'],
      'Sakhipur': ['Sakhipur'],
      'Basail': ['Basail'],
      'Kalihati': ['Kalihati'],
      'Gopalpur': ['Gopalpur'],
      'Dhanora': ['Dhanora'],
      'Mirzapur': ['Mirzapur'],
      'Nagarpur': ['Nagarpur'],
      'Bhuapur': ['Bhuapur'],
      'Delduar': ['Delduar'],
      'Athar Bari': ['Athar Bari'],
    },
    Manikganj: {
      'Manikganj Sadar': ['Manikganj Town'],
      'Singair': ['Singair'],
      'Harirampur': ['Harirampur'],
      'Savar': ['Savar', 'Ashulia'],
      'Dhanbari': ['Dhanbari'],
      'Shibalaya': ['Shibalaya'],
      'Lohajong': ['Lohajong'],
      'Rajibpur': ['Rajibpur'],
    },
    Munshiganj: {
      'Munshiganj Sadar': ['Munshiganj Town'],
      'Gazaria': ['Gazaria'],
      'Tongibari': ['Tongibari'],
      'Setabganj': ['Setabganj'],
      'Serpur': ['Serpur'],
    },
    Narsingdi: {
      'Narsingdi Sadar': ['Narsingdi Town'],
      'Palash': ['Palash'],
      'Ghorashal': ['Ghorashal'],
      'Raipur': ['Raipur'],
      'Madhabdi': ['Madhabdi'],
      'Baraigram': ['Baraigram'],
    },
    Faridpur: {
      'Faridpur Sadar': ['Faridpur Town'],
      'Madhukhali': ['Madhukhali'],
      'Boalmari': ['Boalmari'],
      'Saltha': ['Saltha'],
      'Nagarkanda': ['Nagarkanda'],
      'Charbhadrasan': ['Charbhadrasan'],
      'Krishnapur': ['Krishnapur'],
      'Alfadanga': ['Alfadanga'],
    },
    Rajbari: {
      'Rajbari Sadar': ['Rajbari Town'],
      'Pangsha': ['Pangsha'],
      'Baliakandi': ['Baliakandi'],
      'Kalukhali': ['Kalukhali'],
      'Goalandaghat': ['Goalandaghat'],
      'Rajibpur': ['Rajibpur'],
    },
    Gopalganj: {
      'Gopalganj Sadar': ['Gopalganj Town'],
      'Kashiani': ['Kashiani'],
      'Tungipara': ['Tungipara'],
      'Koolna': ['Koolna'],
      'Murol': ['Murol'],
      'Bajra': ['Bajra'],
    },
    Madaripur: {
      'Madaripur Sadar': ['Madaripur Town'],
      'Shibchar': ['Shibchar'],
      'Kalkini': ['Kalkini'],
      'Rajoir': ['Rajoir'],
      'Baraigram': ['Baraigram'],
    },
    Shariatpur: {
      'Shariatpur Sadar': ['Shariatpur Town'],
      'Bhedarganj': ['Bhedarganj'],
      'Damudya': ['Damudya'],
      'Naria': ['Naria'],
      'Gosair': ['Gosair'],
      'Bajitpur': ['Bajitpur'],
      'Alfadanga': ['Alfadanga'],
    },
    Narail: {
      'Narail Sadar': ['Narail Town'],
      'Kalia': ['Kalia'],
      'Lohagora': ['Lohagora'],
    },
  },
  Chattogram: {
    Chattogram: {
      'Kotwali': ['Chawkbazar', 'Anderkilla', 'Reazuddin Bazar', 'Sadarghat'],
      'Agrabad': ['Agrabad C/A', 'Agrabad Access Road', 'Strand Road'],
      'Nasirabad': ['Nasirabad', 'CDA Avenue', 'GEC Circle', 'Khulshi'],
      'Panchlaish': ['Panchlaish', 'Sugandha', 'Mehedibag'],
      'Halishahar': ['Halishahar', 'Port Area', 'Wasa Colony'],
      'Pahartali': ['Pahartali', 'Cement Crossing'],
      'Double Mooring': ['Double Mooring', 'Karnaphuli'],
      'Bakalia': ['Bakalia', 'Chandgaon'],
      'Chandgaon': ['Chandgaon'],
      'Boalkhali': ['Boalkhali'],
      'Patenga': ['Patenga'],
    },
    "Cox's Bazar": {
      "Cox's Bazar Sadar": ["Cox's Bazar Town", "Kolatoli", 'Laboni Beach'],
      'Teknaf': ['Teknaf', 'St Martin'],
      'Ukhia': ['Ukhia'],
      'Ramu': ['Ramu'],
      'Kutubdia': ['Kutubdia'],
      'Moheshkhali': ['Moheshkhali'],
      'Pekua': ['Pekua'],
    },
    Comilla: {
      'Comilla Sadar': ['Comilla Town', 'Kandirpar', 'Tomsom Bridge'],
      'Comilla Adarsha Sadar': ['Comilla Court', 'Ranir Bazar'],
      'Chandina': ['Chandina'],
      'Choudagram': ['Choudagram'],
      'Brahmanpara': ['Brahmanpara'],
      'Barura': ['Barura'],
      'Buria': ['Buria'],
      'Daudkandi': ['Daudkandi'],
      'Davidhar': ['Davidhar'],
      'Gaila': ['Gaila'],
      'Homna': ['Homna'],
      'Laksham': ['Laksham'],
      'Lalmai': ['Lalmai'],
      'Manoharpur': ['Manoharpur'],
      'Meghna': ['Meghna'],
      'Moor': ['Moor'],
      'Muradnagar': ['Muradnagar'],
      'Nangalkot': ['Nangalkot'],
      'Rajapar': ['Rajapar'],
      'Titas': ['Titas'],
    },
    Feni: {
      'Feni Sadar': ['Feni Town'],
      'Fenchuganj': ['Fenchuganj'],
      'Prasadpur': ['Prasadpur'],
      'Sonagazi': ['Sonagazi'],
      'Phulgazi': ['Phulgazi'],
      'Chhagailnpur': ['Chhagailnpur'],
      'Daganbhuiyan': ['Daganbhuiyan'],
    },
    Noakhali: {
      'Noakhali Sadar': ['Noakhali Town'],
      'Begumganj': ['Begumganj'],
      'Chatkhil': ['Chatkhil'],
      'Companiganj': ['Companiganj'],
      'Hatiya': ['Hatiya'],
      'Kabirhat': ['Kabirhat'],
      'Sandwip': ['Sandwip'],
      'Shubram': ['Shubram'],
      'Sreemongal': ['Sreemongal'],
      'Ramganj': ['Ramganj'],
    },
    Lakshmipur: {
      'Lakshmipur Sadar': ['Lakshmipur Town'],
      'Kamalnagar': ['Kamalnagar'],
      'Keramatganj': ['Keramatganj'],
      'Nagar': ['Nagar'],
      'Rausa': ['Rausa'],
    },
    Chandpur: {
      'Chandpur Sadar': ['Chandpur Town'],
      'Faridgonj': ['Faridgonj'],
      'Haimchar': ['Haimchar'],
      'Kachua': ['Kachua'],
      'Matlab': ['Matlab'],
      'Mohila': ['Mohila'],
      'Shahrasti': ['Shahrasti'],
    },
    Brahmanbaria: {
      'Brahmanbaria Sadar': ['Brahmanbaria Town'],
      'Ashuganj': ['Ashuganj'],
      'Banchhar': ['Banchhar'],
      'Barhatta': ['Barhatta'],
      'Bijoynagar': ['Bijoynagar'],
      'Kasba': ['Kasba'],
      'Nabinagar': ['Nabinagar'],
      'Nazirgaon': ['Nazirgaon'],
      'Shahpur': ['Shahpur'],
      'Tirogaon': ['Tirogaon'],
    },
    Rangamati: {
      'Rangamati Sadar': ['Rangamati Town'],
      'Barkal': ['Barkal'],
      'Kaptai': ['Kaptai'],
      'Kawkhali': ['Kawkhali'],
      'Langadu': ['Langadu'],
      'Naniyachar': ['Naniyachar'],
      'Rajasthali': ['Rajasthali'],
    },
  },
  Rajshahi: {
    Rajshahi: {
      'Rajshahi City': ['Shaheb Bazar', 'New Market Rajshahi', 'Laxmipur', 'Uposhohor'],
      'Boalia': ['Boalia'],
      'Rajpara': ['Rajpara'],
      'Motihar': ['Motihar'],
      'Chandra': ['Chandra'],
      'Godagari': ['Godagari'],
      'Puthia': ['Puthia'],
      'Tanore': ['Tanore'],
    },
    Bogura: {
      'Bogura Sadar': ['Bogura Town', 'Satmatha'],
      'Dhunat': ['Dhunat'],
      'Dhupchanchia': ['Dhupchanchia'],
      'Gabtali': ['Gabtali'],
      'Kahaloo': ['Kahaloo'],
      'Nandigram': ['Nandigram'],
      'Shibganj': ['Shibganj'],
      'Sonatala': ['Sonatala'],
    },
    Naogaon: {
      'Naogaon Sadar': ['Naogaon Town'],
      'Badalgachi': ['Badalgachi'],
      'Hatghar': ['Hatghar'],
      'Mahadeebpur': ['Mahadeebpur'],
      'Mitra': ['Mitra'],
      'Niamatpur': ['Niamatpur'],
      'Param': ['Param'],
      'Porsha': ['Porsha'],
      'Sapahar': ['Sapahar'],
    },
    Natore: {
      'Natore Sadar': ['Natore Town'],
      'Bagram': ['Bagram'],
      'Gopalpur': ['Gopalpur'],
      'Lalpur': ['Lalpur'],
      'Shara': ['Shara'],
    },
    Chapainawabganj: {
      'Chapainawabganj Sadar': ['Chapainawabganj Town'],
      'Bhabaniganj': ['Bhabaniganj'],
      'Gomostapur': ['Gomostapur'],
      'Nachol': ['Nachol'],
      'Shibganj': ['Shibganj'],
    },
    Pabna: {
      'Pabna Sadar': ['Pabna Town'],
      'Atghoria': ['Atghoria'],
      'Bera': ['Bera'],
      'Bharara': ['Bharara'],
      'Chatmohar': ['Chatmohar'],
      'Faridpur': ['Faridpur'],
      'Ishwardi': ['Ishwardi'],
      'Kashtor': ['Kashtor'],
      'Santhia': ['Santhia'],
      'Sujanagar': ['Sujanagar'],
    },
    Sirajganj: {
      'Sirajganj Sadar': ['Sirajganj Town'],
      'Belkuchi': ['Belkuchi'],
      'Chauhali': ['Chauhali'],
      'Gowng': ['Gowng'],
      'Kamarkhand': ['Kamarkhand'],
      'Kashinath': ['Kashinath'],
      'Raigonj': ['Raigonj'],
      'Salanga': ['Salanga'],
      'Tarash': ['Tarash'],
      'Ullapara': ['Ullapara'],
    },
    Joypurhat: {
      'Joypurhat Sadar': ['Joypurhat Town'],
      'Akkelpur': ['Akkelpur'],
      'Kalai': ['Kalai'],
      'Khetlal': ['Khetlal'],
      'Panchbibi': ['Panchbibi'],
    },
  },
  Khulna: {
    Khulna: {
      'Khulna City': ['Khulna New Market', 'Boyra', 'Sonadanga', 'Shibbari', 'Daulatpur'],
      'Khalishpur': ['Khalishpur', 'KDA Avenue'],
      'Daulatpur': ['Daulatpur'],
      'Dumuria': ['Dumuria'],
      'Khanjahan': ['Khanjahan'],
      'Paikgachha': ['Paikgachha'],
      'Rupsa': ['Rupsa'],
    },
    Jessore: {
      'Jessore Sadar': ['Jessore Town'],
      'Abhaynagar': ['Abhaynagar'],
      'Bagherpara': ['Bagherpara'],
      'Chougachha': ['Chougachha'],
      'Jhikorgachha': ['Jhikorgachha'],
      'Keshobpur': ['Keshobpur'],
      'Manirampur': ['Manirampur'],
      'Sarankhola': ['Sarankhola'],
      'Sharsha': ['Sharsha'],
    },
    Khustia: {
      'Kushtia Sadar': ['Kushtia Town'],
      'Bheramara': ['Bheramara'],
      'Daipap': ['Daipap'],
      'Kumarkhali': ['Kumarkhali'],
      'Mirpur': ['Mirpur'],
    },
    Magura: {
      'Magura Sadar': ['Magura Town'],
      'Mohammadpur': ['Mohammadpur'],
      'Shalikha': ['Shalikha'],
      'Sreepur': ['Sreepur'],
    },
    Meherpur: {
      'Meherpur Sadar': ['Meherpur Town'],
      'Gangni': ['Gangni'],
      'Mujibnagar': ['Mujibnagar'],
    },
    Narail: {
      'Narail Sadar': ['Narail Town'],
      'Kalia': ['Kalia'],
      'Lohagora': ['Lohagora'],
    },
    Satkhira: {
      'Satkhira Sadar': ['Satkhira Town'],
      'Assasuni': ['Assasuni'],
      'Debhata': ['Debhata'],
      'Kalaroa': ['Kalaroa'],
      'Kaliganj': ['Kaliganj'],
      'Shyamnagar': ['Shyamnagar'],
      'Tala': ['Tala'],
    },
    Bagerhat: {
      'Bagerhat Sadar': ['Bagerhat Town'],
      'Betagi': ['Betagi'],
      'Bishnupur': ['Bishnupur'],
      'Chitalmari': ['Chitalmari'],
      'Fakirhat': ['Fakirhat'],
      'Kachua': ['Kachua'],
      'Mollahat': ['Mollahat'],
      'Morrelganj': ['Morrelganj'],
      'Rampal': ['Rampal'],
      'Sarankhola': ['Sarankhola'],
    },
    Chuadanga: {
      'Chuadanga Sadar': ['Chuadanga Town'],
      'Alamdanga': ['Alamdanga'],
      'Damurhuda': ['Damurhuda'],
      'Doulatnagar': ['Doulatnagar'],
      'Jeevanagar': ['Jeevanagar'],
    },
  },
  Barishal: {
    Barishal: {
      'Barishal City': ['Barishal Town', 'Notullabad', 'Rupatali'],
      'Barishal Sadar': ['Sadar Road'],
      'Bakerganj': ['Bakerganj'],
      'Gouranadi': ['Gouranadi'],
      'Hijla': ['Hijla'],
      'Karnaphuli': ['Karnaphuli'],
      'Mathergopal': ['Mathergopal'],
      'Nazirpur': ['Nazirpur'],
    },
    Jhalokathi: {
      'Jhalokathi Sadar': ['Jhalokathi Town'],
      'Kathalia': ['Kathalia'],
      'Nalchity': ['Nalchity'],
      'Rajapur': ['Rajapur'],
    },
    Pirojpur: {
      'Pirojpur Sadar': ['Pirojpur Town'],
      'Bhandaria': ['Bhandaria'],
      'Kawkhali': ['Kawkhali'],
      'Mathura': ['Mathura'],
      'Nesarabad': ['Nesarabad'],
      'Zianglar': ['Zianglar'],
    },
    Barguna: {
      'Barguna Sadar': ['Barguna Town'],
      'Amtali': ['Amtali'],
      'Bamna': ['Bamna'],
      'Betagi': ['Betagi'],
      'Patharghata': ['Patharghata'],
    },
    Patuakhali: {
      'Patuakhali Sadar': ['Patuakhali Town'],
      'Bauphal': ['Bauphal'],
      'Dash': ['Dash'],
      'Kalapara': ['Kalapara'],
      'Khepupara': ['Khepupara'],
      'Mirjaganj': ['Mirjaganj'],
    },
  },
  Sylhet: {
    Sylhet: {
      'Sylhet City': ['Zindabazar', 'Amberkhana', 'Bandarbazar', 'Kumarpara', 'Chowhatta', 'Subid Bazar'],
      'Sylhet Sadar': ['South Surma', 'Kuchai'],
      'Beanibazar': ['Beanibazar'],
      'Bishwanath': ['Bishwanath'],
      'Dakkhin': ['Dakkhin'],
      'Fenchuganj': ['Fenchuganj'],
      'Gowainghat': ['Gowainghat'],
      'Jaintiapur': ['Jaintiapur'],
      'Kanaighat': ['Kanaighat'],
      'Zabir': ['Zabir'],
    },
    Habiganj: {
      'Habiganj Sadar': ['Habiganj Town'],
      'Ajmiriganj': ['Ajmiriganj'],
      'Bahubal': ['Bahubal'],
      'Baniachong': ['Baniachong'],
      'Chunarughat': ['Chunarughat'],
      'Lakhai': ['Lakhai'],
      'Madhabpur': ['Madhabpur'],
      'Nabiganj': ['Nabiganj'],
      'Sayani': ['Sayani'],
    },
    MoulviBazar: {
      'Moulvibazar Sadar': ['Moulvibazar Town'],
      'Barlekha': ['Barlekha'],
      'Juri': ['Juri'],
      'Kamalganj': ['Kamalganj'],
      'Rajnagar': ['Rajnagar'],
      'Sreemangal': ['Sreemangal'],
    },
    Sunamganj: {
      'Sunamganj Sadar': ['Sunamganj Town'],
      'Bishwanath': ['Bishwanath'],
      'Chhatak': ['Chhatak'],
      'Derai': ['Derai'],
      'Gowainghat': ['Gowainghat'],
      'Jaintiapur': ['Jaintiapur'],
      'Shalla': ['Shalla'],
      'Taherpur': ['Taherpur'],
      'Zakiganj': ['Zakiganj'],
    },
  },
  Rangpur: {
    Rangpur: {
      'Rangpur City': ['Rangpur Town', 'Dhap', 'Jahaj Company More', 'Central Road'],
      'Rangpur Sadar': ['Rangpur Sadar'],
      'Badarganj': ['Badarganj'],
      'Gangachara': ['Gangachara'],
      'Kaunia': ['Kaunia'],
      'Pirgacha': ['Pirgacha'],
      'Pirganj': ['Pirganj'],
      'Taraganj': ['Taraganj'],
    },
    Dinajpur: {
      'Dinajpur Sadar': ['Dinajpur Town'],
      'Birganj': ['Birganj'],
      'Biral': ['Biral'],
      'Birampur': ['Birampur'],
      'Birbali': ['Birbali'],
      'Chirirbandar': ['Chirirbandar'],
      'Ghoraghat': ['Ghoraghat'],
      'Hakimpur': ['Hakimpur'],
      'Kaharole': ['Kaharole'],
      'Kochas': ['Kochas'],
      'Mahadevpur': ['Mahadevpur'],
      'Manikpur': ['Manikpur'],
      'Nawabganj': ['Nawabganj'],
      'Parbatipur': ['Parbatipur'],
      'Phulbari': ['Phulbari'],
    },
    Gaibandha: {
      'Gaibandha Sadar': ['Gaibandha Town'],
      'Bogula': ['Bogula'],
      'Dimla': ['Dimla'],
      'Dolphair': ['Dolphair'],
      'Gobindaganj': ['Gobindaganj'],
      'Palashbari': ['Palashbari'],
      'Phulchhari': ['Phulchhari'],
      'Sadullapur': ['Sadullapur'],
      'Sundarganj': ['Sundarganj'],
    },
    Kurigram: {
      'Kurigram Sadar': ['Kurigram Town'],
      'Bhurungamari': ['Bhurungamari'],
      'Magurhat': ['Magurhat'],
      'Nageshwari': ['Nageshwari'],
      'Phulbari': ['Phulbari'],
      'Rajarhat': ['Rajarhat'],
      'Rowmari': ['Rowmari'],
      'Ulipur': ['Ulipur'],
    },
    Lalmonirhat: {
      'Lalmonirhat Sadar': ['Lalmonirhat Town'],
      'Aditmari': ['Aditmari'],
      'Hatibanda': ['Hatibanda'],
      'Kaliganj': ['Kaliganj'],
      'Patgram': ['Patgram'],
    },
    Nilphamari: {
      'Nilphamari Sadar': ['Nilphamari Town'],
      'Domar': ['Domar'],
      'Jaldhaka': ['Jaldhaka'],
      'Param': ['Param'],
      'Saidpur': ['Saidpur'],
    },
    Thakurgaon: {
      'Thakurgaon Sadar': ['Thakurgaon Town'],
      'Baliadangi': ['Baliadangi'],
      'Haripur': ['Haripur'],
      'Jhawani': ['Jhawani'],
      'Pirpur': ['Pirpur'],
      'Ranisonkhola': ['Ranisonkhola'],
    },
    Panchagarh: {
      'Panchagarh Sadar': ['Panchagarh Town'],
      'Boda': ['Boda'],
      'Devnagar': ['Devnagar'],
      'Tetulia': ['Tetulia'],
    },
  },
  Mymensingh: {
    Mymensingh: {
      'Mymensingh City': ['Mymensingh Town', 'Ganginar Par', 'Chorpara', 'Maskanda'],
      'Mymensingh Sadar': ['Mymensingh Sadar'],
      'Bhaluka': ['Bhaluka'],
      'Fulpur': ['Fulpur'],
      'Gouripur': ['Gouripur'],
      'Haluaghat': ['Haluaghat'],
      'Ishwarganj': ['Ishwarganj'],
      'Muktagachha': ['Muktagachha'],
      'Nakla': ['Nakla'],
      'Nandail': ['Nandail'],
      'Phulpur': ['Phulpur'],
      'Tarakanda': ['Tarakanda'],
      'Trishal': ['Trishal'],
      'Uttara': ['Uttara'],
    },
    Jamalpur: {
      'Jamalpur Sadar': ['Jamalpur Town'],
      'Boktar': ['Boktar'],
      'Dewanganj': ['Dewanganj'],
      'Islampur': ['Islampur'],
      'Madarganj': ['Madarganj'],
      'Melandaha': ['Melandaha'],
      'Narayanpur': ['Narayanpur'],
      'Sarishabari': ['Sarishabari'],
    },
    Netrokona: {
      'Netrakona Sadar': ['Netrakona Town'],
      'Atpara': ['Atpara'],
      'Barhatta': ['Barhatta'],
      'Durgapur': ['Durgapur'],
      'Kalmakanda': ['Kalmakanda'],
      'Kendua': ['Kendua'],
      'Madan': ['Madan'],
      'Mohanpur': ['Mohanpur'],
      'Puranabazar': ['Puranabazar'],
      'Sharikhali': ['Sharikhali'],
    },
    Sherpur: {
      'Sherpur Sadar': ['Sherpur Town'],
      'Jel Khan': ['Jel Khan'],
      'Nakhla': ['Nakhla'],
      'Sribari': ['Sribari'],
    },
  },
};

export const getDivisions = () => Object.keys(bangladeshLocations);

export const getDistricts = (division) => {
  if (!division || !bangladeshLocations[division]) return [];
  return Object.keys(bangladeshLocations[division]);
};

export const getUpazillas = (division, district) => {
  if (!division || !district) return [];
  const div = bangladeshLocations[division];
  if (!div || !div[district]) return [];
  return Object.keys(div[district]);
};

export const getAreas = (division, district, upazilla) => {
  if (!division || !district || !upazilla) return [];
  const div = bangladeshLocations[division];
  if (!div) return [];
  const dist = div[district];
  if (!dist) return [];
  return dist[upazilla] || [];
};